```{r,echo=FALSE,message=FALSE,warning=FALSE}
library(lidR)
library(ggplot2)
library(raster)
library(sf)
library(forcats)

r3dDefaults = rgl::r3dDefaults
m = structure(c(0.921, -0.146, 0.362, 0, 0.386, 0.482, -0.787, 0, 
-0.06, 0.864, 0.5, 0, 0, 0, 0, 1), .Dim = c(4L, 4L))
r3dDefaults$FOV = 50
r3dDefaults$userMatrix = m
r3dDefaults$zoom = 0.75

knitr::opts_chunk$set(
  comment =  "#>", 
  collapse = TRUE,
  fig.align = "center")

rgl::setupKnitr(autoprint = TRUE)

roads <- st_read("data/03/roads.shp")

```

# Tips and Tricks {#sec-tips-and-tricks}

Following the update of road segments using the `ALSroads`package users may wish to edit data, filter results, or plot outcomes. Here, we provide code snippets intended to provide users with some basic data manipulation and interpretation tools.

## Casting Roads to Linestring

Existing road networks may be multistring features, the `measure_roads()` function requires that roads are linestrings. Changing multistring features to linestrings requires the `st_cast()` function from the `sf` package (refer to the [sf vignette](https://cran.r-project.org/web/packages/sf/sf.pdf) for detailed information).

```r
roads <- st_cast(roads, "LINESTRING")
```

## Adding an ID Column

Existing road networks frequently include FID and ID columns that will help users select individual roads. In some cases, however, road networks have been edited or updated and the ID/FID columns are missing information.

Users may wish to add a new ID column that specifically relate to the roads on which the ALSroads method was applied. In that case, users can add and populate a new column using the `rowid_to_column` from the `tibble` package (refer to the [tibble vignette](https://cloud.r-project.org/web/packages/tibble/tibble.pdf) for detailed information).

``` r
roads <- tibble::rowid_to_column(roads, "NUM")
```

## Selecting Specific Roads

``` r
road_subset <- roads %>%
  dplyr::filter(NUM %in% c(0:10))
```

## Plotting Data

## Saving Data

## Reconnecing Roads
